// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDco8n49uS4gT4eZHEGM4ILyirGZ62qaqI',
    appId: '1:323701786497:web:b613382c261b1a28270a80',
    messagingSenderId: '323701786497',
    projectId: 'foodhubforeveryone',
    authDomain: 'foodhubforeveryone.firebaseapp.com',
    storageBucket: 'foodhubforeveryone.appspot.com',
    measurementId: 'G-MX06YKXRX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgl7KFrhdu0XC0UYZPQmPQOU2N95wbUA0',
    appId: '1:323701786497:android:251c9b9a93bcd1b6270a80',
    messagingSenderId: '323701786497',
    projectId: 'foodhubforeveryone',
    storageBucket: 'foodhubforeveryone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBarZYful-W1Fq-1cElqg0nXo8DjG6pjl4',
    appId: '1:323701786497:ios:fa3aac84c6629d81270a80',
    messagingSenderId: '323701786497',
    projectId: 'foodhubforeveryone',
    storageBucket: 'foodhubforeveryone.appspot.com',
    iosClientId: '323701786497-8lq0ga99v226m574isj80m8io35h3vpa.apps.googleusercontent.com',
    iosBundleId: 'com.james.foodHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBarZYful-W1Fq-1cElqg0nXo8DjG6pjl4',
    appId: '1:323701786497:ios:6bd08d042049f3ce270a80',
    messagingSenderId: '323701786497',
    projectId: 'foodhubforeveryone',
    storageBucket: 'foodhubforeveryone.appspot.com',
    iosClientId: '323701786497-629cq5t4har49fgva0k0tcjh1758lsh4.apps.googleusercontent.com',
    iosBundleId: 'com.james.foodHubApp.RunnerTests',
  );
}
