// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFMv1XltGyYS1kssn-3URoaM9xHZ3bvnA',
    appId: '1:442255127404:web:d9695641e56706a1e8b949',
    messagingSenderId: '442255127404',
    projectId: 'food-hub-502c1',
    authDomain: 'food-hub-502c1.firebaseapp.com',
    storageBucket: 'food-hub-502c1.appspot.com',
    measurementId: 'G-1CSES5MM4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-E78WYnz9k2neNbvZi3qO-FDrH5byUk',
    appId: '1:442255127404:android:867eb8b82a825346e8b949',
    messagingSenderId: '442255127404',
    projectId: 'food-hub-502c1',
    storageBucket: 'food-hub-502c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6Eeldwekon6QVefxytTI_j2EjLBOddA',
    appId: '1:442255127404:ios:323b49f36e064b12e8b949',
    messagingSenderId: '442255127404',
    projectId: 'food-hub-502c1',
    storageBucket: 'food-hub-502c1.appspot.com',
    iosClientId: '442255127404-6v2kjeg1c0d4mq9avqdp4je4ago8pm2a.apps.googleusercontent.com',
    iosBundleId: 'com.james.foodHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6Eeldwekon6QVefxytTI_j2EjLBOddA',
    appId: '1:442255127404:ios:6228e7c4a7003f3ee8b949',
    messagingSenderId: '442255127404',
    projectId: 'food-hub-502c1',
    storageBucket: 'food-hub-502c1.appspot.com',
    iosClientId: '442255127404-mpcmkvtc9q7lmpad050sambg6u16top4.apps.googleusercontent.com',
    iosBundleId: 'com.james.foodHubApp.RunnerTests',
  );
}
